# Generated by Django 3.2.6 on 2021-08-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hihat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.beat')),
            ],
        ),
        migrations.CreateModel(
            name='Kick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.beat')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Snare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.beat')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField()),
                ('two', models.BooleanField()),
                ('three', models.BooleanField()),
                ('four', models.BooleanField()),
                ('five', models.BooleanField()),
                ('six', models.BooleanField()),
                ('seven', models.BooleanField()),
                ('eight', models.BooleanField()),
                ('hihat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.hihat')),
                ('kick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.kick')),
                ('snare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.snare')),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='snippets.snippet'),
        ),
    ]
