# Generated by Django 3.2.6 on 2021-08-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='hihat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.hihat'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='kick',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.kick'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='snare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.snare'),
        ),
    ]
