# Generated by Django 3.2.6 on 2021-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210824_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='eight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='five',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='four',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='seven',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='six',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='three',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='two',
            field=models.BooleanField(default=False),
        ),
    ]
